# Version simplifiée - Juste l'API avec l'agent exemple
version: '3.8'

volumes:
  postgres-data:
    driver: local

services:
  redis:
    image: redis:6
    restart: unless-stopped

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: langgraph
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  langgraph:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8123:8000"
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_URI: redis://redis:6379
      DATABASE_URI: postgres://postgres:postgres@postgres:5432/langgraph?sslmode=disable
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY:-}
      LANGSMITH_TRACING: ${LANGSMITH_TRACING:-false}
    volumes:
      - ./agents:/app/agents:ro
